#!/bin/sh
#This script used for copy file to target directory
BUILD_DIR=$1
THIS_NAME=$2

mkdir -p ${PLATFORM_TARGET_RELEASE_DIRECTORY}/include
mkdir -p ${PLATFORM_TARGET_RELEASE_DIRECTORY}/lib
mkdir -p ${PLATFORM_TARGET_RELEASE_DIRECTORY}/test
mkdir -p ${PLATFORM_TARGET_RELEASE_DIRECTORY}/test_code

cp -af include/* ${PLATFORM_TARGET_RELEASE_DIRECTORY}/include
cp -af test/test* ${PLATFORM_TARGET_RELEASE_DIRECTORY}/test_code
cp -af ${BUILD_DIR}/${THIS_NAME}/libs/* ${PLATFORM_TARGET_RELEASE_DIRECTORY}/lib
cp -af ${BUILD_DIR}/${THIS_NAME}/tests/* ${PLATFORM_TARGET_RELEASE_DIRECTORY}/test
